### PR TITLE
fix: components' `displayName` typos

### LINKED ISSUE #611: typo: table component
Hey, guys, I've just spotted a small typo here. 

https://github.com/geist-org/react/blob/b6f6cda90f00aba475b114dd02ad39efd6470321/components/table/table-column.tsx#L51

Sorry for pointing out instead of fixing it. I'd love to contribute, even if only fixing typos, but I'm afraid I could mess up commits or something down the lines. Noob feelings 🐣

### PR DESCRIPTION
**Pull request by moatorres**
## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

This PR fixes #611 typos on some components' `displayName`

### CODE REVIEW

File: components/table/table-head.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ const defaultProps = {
 type NativeAttrs = Omit<React.HTMLAttributes<any>, keyof Props<any>>
 export type TableHeadProps<TableDataItem> = Props<TableDataItem> & NativeAttrs
 
-const makeColgroup = <TableDataItem,>(
```
Comment (moatorres) [inline components/table/table-head.tsx:18]: I guess it shuld be there? 🤷‍♂️
